#!/bin/bash

# Let python find the script module.
export PYTHONPATH="$(dirname "$(readlink -f "$0")")"

# Run module as script (or rather script as module, in our case)...
exec python3 -m mcstatus_cvn "$@"
